### ISSUE TITLE
安装到一半的时候忘了重启了系统，然后就提示错误了

### ISSUE THREAD

**Issue by serra01** [FHWWC/FCLiveTool#2]
![QQ截图20230812081055](https://github.com/FHWWC/FCLiveTool/assets/37280035/c2194ea8-0665-4cbe-9557-5407d5254987)

**Comment by FHWWC** [comment]
请将证书安装到“受信任的根证书颁发机构”，cer证书在压缩包里。
![屏幕截图 2023-08-13 021834](https://github.com/FHWWC/FCLiveTool/assets/29021624/4e4878fb-d75b-447a-88a0-54ac304801ff)

**Comment by serra01** [comment]
> 请将证书安装到“受信任的根证书颁发机构”，cer证书在压缩包里。 ![屏幕截图 2023-08-13 021834](https://user-images.githubusercontent.com/29021624/260251547-4e4878fb-d75b-447a-88a0-54ac304801ff.png)

谢谢大佬，能用了
